# Hotel Demand Analysis

Data Cleaning and Exploration

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('hotel_bookings_cleaned.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

Sort and filter columns

In [3]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [4]:
hotel_bookings=df[['hotel', 'is_canceled', 'lead_time','reservation_status_date', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'customer_type', 'adr',
       'reservation_status',
       ]]

In [5]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,reservation_status_date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015-07-01,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,3,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015-07-01,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,4,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015-07-02,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015-07-02,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015-07-03,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,0,Transient,98.0,Check-Out

In [6]:
hotel_bookings.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
reservation_status_date            object
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
booking_changes                     int64
customer_type                      object
adr                               float64
reservation_status                 object
dtype: object

In [7]:
hotel_bookings['reservation_status_date']=hotel_bookings['reservation_status_date'].astype('datetime64[ns]')

C:\Users\Victor\AppData\Local\Temp\ipykernel_3640\545529353.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_bookings['reservation_status_date']=hotel_bookings['reservation_status_date'].astype('datetime64[ns]')

In [8]:
hotel_bookings.dtypes

hotel                                     object
is_canceled                                int64
lead_time                                  int64
reservation_status_date           datetime64[ns]
stays_in_weekend_nights                    int64
stays_in_week_nights                       int64
adults                                     int64
children                                 float64
babies                                     int64
meal                                      object
country                                   object
market_segment                            object
distribution_channel                      object
is_repeated_guest                          int64
previous_cancellations                     int64
previous_bookings_not_canceled             int64
booking_changes                            int64
customer_type                             object
adr                                      float64
reservation_status                        object
dtype: object

In [9]:
hotel_bookings.isna().sum()

hotel                               0
is_canceled                         0
lead_time                           0
reservation_status_date             0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
booking_changes                     0
customer_type                       0
adr                                 0
reservation_status                  0
dtype: int64

In [10]:
hotel_bookings[hotel_bookings['country'].isna()]

,hotel,is_canceled,lead_time,reservation_status_date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,customer_type,adr,reservation_status
30,Resort Hotel,0,118,2015-07-15,4,10,1,0.0,0,BB,NaN,Direct,Direct,0,0,0,2,Transient,62.0,Check-Out
4127,Resort Hotel,1,0,2016-02-15,0,0,0,0.0,0,SC,NaN,Offline TA/TO,TA/TO,0,0,0,0,Transient,0.0,Canceled
7092,Resort Hotel,1,8,2016-07-20,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,0,Transient,73.0,Canceled
7860,Resort Hotel,1,39,2016-07-22,0,5,2,0.0,0,HB,NaN,Direct,Direct,0,0,0,0,Transient,159.0,Canceled
8779,Resort Hotel,1,0,2016-10-13,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,0,Transient,50.0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65908,City Hotel,1,0,2017-04-10,0,0,0,0.0,0,SC,NaN,Complementary,Corporate,0,0,0,0,Transient,0.0,Canceled
65909,City Hotel,1,0,2017-04-10,0,0,0,0.0,0,SC,NaN,Complementary,Corporate,0,0,0,0,Transient,0.0,Canceled
65910,City Hotel,1,0,2017-04-10,0,0,0,0.0,0,SC,NaN,Complementary,Corporate,0,0,0,0,Transient,0.0,Canceled
80830,City Hotel,0,4,2015-11-26,1,2,1,0.0,0,BB,NaN,Groups,TA/TO,0,0,0,0,Transient-Party,70.0,Check-Out
101488,City Hotel,0,1,2016-11-17,2,2,2,0.0,0,BB,NaN,Direct,Direct,0,0,0,0,Group,105.0,Check-Out

In [11]:
PN =df[df['is_canceled']== 1]
PN

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.0,0,0,Canceled,2015-06-23
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.0,0,2,Canceled,2015-05-11
32,Resort Hotel,1,96,2015,July,27,1,2,8,2,...,No Deposit,NaN,NaN,0,Transient,108.3,0,2,Canceled,2015-05-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110280,City Hotel,1,132,2017,April,17,25,0,0,0,...,No Deposit,9.0,NaN,0,Transient,0.0,0,3,Canceled,2017-04-25
111355,City Hotel,1,4,2017,June,23,5,1,0,1,...,No Deposit,NaN,238.0,0,Transient,65.0,0,0,Canceled,2017-06-05
111924,City Hotel,1,7,2017,May,22,31,0,1,1,...,No Deposit,NaN,238.0,0,Transient,65.0,0,0,Canceled,2017-05-31
111925,City Hotel,1,6,2017,July,29,17,1,0,1,...,No Deposit,NaN,238.0,0,Transient,65.0,0,0,No-Show,2017-07-17
117295,City Hotel,1,0,2017,August,31,2,0,2,1,...,No Deposit,NaN,40.0,0,Transient,65.0,0,1,No-Show,2017-08-02

In [12]:
hotel_bookings['country'].fillna('Not Supplied', inplace=True)

C:\Users\Victor\AppData\Local\Temp\ipykernel_3640\2805530227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_bookings['country'].fillna('Not Supplied', inplace=True)

In [13]:
hotel_bookings.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
reservation_status_date           0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          4
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
booking_changes                   0
customer_type                     0
adr                               0
reservation_status                0
dtype: int64

In [14]:
hotel_bookings['children'].fillna( 0 ,inplace=True)

C:\Users\Victor\AppData\Local\Temp\ipykernel_3640\4129883758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_bookings['children'].fillna( 0 ,inplace=True)

In [15]:
hotel_bookings.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
reservation_status_date           0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
booking_changes                   0
customer_type                     0
adr                               0
reservation_status                0
dtype: int64

In [16]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,reservation_status_date,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,customer_type,adr,reservation_status
0,Resort Hotel,0,342,2015-07-01,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,3,Transient,0.0,Check-Out
1,Resort Hotel,0,737,2015-07-01,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,4,Transient,0.0,Check-Out
2,Resort Hotel,0,7,2015-07-02,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,0,Transient,75.0,Check-Out
3,Resort Hotel,0,13,2015-07-02,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,0,Transient,75.0,Check-Out
4,Resort Hotel,0,14,2015-07-03,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,0,Transient,98.0,Check-Out

In [ ]:
#hotel_bookings.to_csv('HotelBookingsAnalysis.csv',index=False)